remote:
    url: http://dev.kode-datacenter.net:8082
datasets:
-   path: resources\*
    name: bands
    desc: All bands
    label: bands
    type: table
    meta:
        tag: null
        commit: 62e3cb02f0033bb0165239e344cbc48bc45c5447
