remote:
    url: http://dev.kode-datacenter.net:8082
datasets:
-   path: resources\*
    name: bands
    desc: All bands
    label: bands
    type: table
    meta:
        tag: null
        commit: bf1ef535d07899462c080850df329569ad46c5e0
